# Generated by Django 6.0 on 2026-01-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
