# Generated by Django 6.0 on 2026-01-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_schedule',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session_schedule',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('LEARNER', 'Learner'), ('TEACHER', 'Teacher')], max_length=10, null=True),
        ),
    ]
