# Generated by Django 6.0 on 2026-01-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
